#@host = https://dpva659zgizmt.cloudfront.net/dev
#@host = https://8tsv2zqthl.execute-api.us-east-1.amazonaws.com/dev

#@host = http://d1gmq5xqc8h8zh.cloudfront.net/dev
@host = https://vixg5hyebe.execute-api.us-east-1.amazonaws.com/dev


### GET Chrome version
GET {{host}}/version-info

### GET screenshot
GET {{host}}/screenshot?resource=M52Dd2mSHE1.png

### GET screenshot 2
GET {{host}}/screenshot?resource=7lqbiwzn76F.png

### GET screenshot 3
GET {{host}}/screenshot?resource=YquEEqe2NjB.png

### GET invalid request
GET {{host}}/screenshot?resource=7lqbiwzn76e123

### GET invalid user
GET {{host}}/screenshot?resource=7lqbiwzn76e.png

### GET invalid user from source
GET https://www.aventrix.com/users/7lqbiwzn76a/infographic
