service: aws

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    # This will define an environment variable BUCKET with the name of the bucket created in the resources section
    # BUCKET: 
    #   Ref: ScreenshotsBucket
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true
  # This describes the permissions common to all the lambdas
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "s3:*"
  #     Resource:
  #         - "*"

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  s3Bucket: aventrix-screenshot
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars

functions:
  version-info:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/version.default
    events:
      - http:
          path: version-info
          method: get

  screenshot:
    description: Headless Chrome Serverless-framework screenshot example
    memorySize: 1536
    timeout: 30
    handler: src/handlers/screenshot.default
    events:
      - http:
          path: screenshot
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Screenshot CloudFront Distribution
          Enabled: true
          PriceClass: PriceClass_100
          DefaultCacheBehavior:
            AllowedMethods:
            - HEAD
            - GET
            TargetOriginId: ScreenshotLambdaOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              QueryString: true
          Origins:
          - Id: ScreenshotLambdaOrigin
            DomainName:
              Fn::Join:
                - ""
                - - Ref: ApiGatewayRestApi
                - ".execute-api.us-east-1.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
